"""initial schema

Revision ID: c390315de59f
Revises:
Create Date: 2026-09-21 17:15:17.969451

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c390315de59f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_bot', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('background_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled')", name=op.f('ck_background_jobs_valid_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_background_jobs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_background_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_background_jobs_idempotency_key'))
    )
    op.create_index('ix_background_jobs_claim', 'background_jobs', ['status', 'available_at'], unique=False)
    op.create_index('ix_background_jobs_user', 'background_jobs', ['user_id'], unique=False)
    op.create_table('calendar_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('task', 'event', name='itemkind'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='itemstatus'), server_default='scheduled', nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', name='itempriority'), server_default='normal', nullable=False),
    sa.Column('source', sa.String(length=32), server_default='bot', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('task', 'event')", name=op.f('ck_calendar_items_valid_kind')),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high')", name=op.f('ck_calendar_items_valid_priority')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_items'))
    )
    op.create_index('ix_calendar_items_user_start', 'calendar_items', ['user_id', 'starts_at'], unique=False)
    op.create_index('ix_calendar_items_user_status', 'calendar_items', ['user_id', 'status', 'starts_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='chatrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='telegram', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_messages_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_user_created', 'chat_messages', ['user_id', 'created_at'], unique=False)
    op.create_table('user_facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('provenance', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'confirmed', 'rejected', 'superseded', name='factstatus'), server_default='proposed', nullable=False),
    sa.Column('superseded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name=op.f('ck_user_facts_valid_confidence')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_facts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_facts'))
    )
    op.create_index('ix_user_facts_user_status', 'user_facts', ['user_id', 'status', 'category'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('digest_time', sa.Time(), server_default='08:00:00', nullable=False),
    sa.Column('motivation_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('workout_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'completed', 'skipped', 'cancelled', name='workoutstatus'), server_default='completed', nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_logs'))
    )
    op.create_index('ix_workout_logs_user_started', 'workout_logs', ['user_id', 'started_at'], unique=False)
    op.create_table('digests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_digests_job_id_background_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_digests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digests')),
    sa.UniqueConstraint('user_id', 'digest_date', name='uq_digests_user_day')
    )
    op.create_table('reminders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('calendar_item_id', sa.BigInteger(), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), server_default='absolute', nullable=False),
    sa.Column('offset_minutes', sa.Integer(), nullable=True),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'cancelled', 'failed', name='reminderstatus'), server_default='pending', nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("trigger_type IN ('absolute', 'item_linked')", name=op.f('ck_reminders_valid_trigger_type')),
    sa.ForeignKeyConstraint(['calendar_item_id'], ['calendar_items.id'], name=op.f('fk_reminders_calendar_item_id_calendar_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_reminders_job_id_background_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_table('user_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('telegram_file_unique_id', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('queued', 'downloading', 'extracting', 'chunking', 'embedding', 'indexed', 'failed', 'rejected', name='filestate'), server_default='queued', nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('queued','downloading','extracting','chunking','embedding','indexed','failed','rejected')", name=op.f('ck_user_files_valid_state')),
    sa.ForeignKeyConstraint(['job_id'], ['background_jobs.id'], name=op.f('fk_user_files_job_id_background_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_user_files_storage_key'))
    )
    op.create_table('file_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['user_files.id'], name=op.f('fk_file_chunks_file_id_user_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_file_chunks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_chunks'))
    )
    op.create_index('ix_file_chunks_user', 'file_chunks', ['user_id'], unique=False)
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_file_chunks_embedding_hnsw "
        "ON file_chunks USING hnsw (embedding vector_cosine_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_file_chunks_embedding_hnsw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_chunks_user', table_name='file_chunks')
    op.drop_table('file_chunks')
    op.drop_table('user_files')
    op.drop_table('reminders')
    op.drop_table('digests')
    op.drop_index('ix_workout_logs_user_started', table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_table('user_settings')
    op.drop_index('ix_user_facts_user_status', table_name='user_facts')
    op.drop_table('user_facts')
    op.drop_index('ix_chat_messages_user_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_calendar_items_user_status', table_name='calendar_items')
    op.drop_index('ix_calendar_items_user_start', table_name='calendar_items')
    op.drop_table('calendar_items')
    op.drop_index('ix_background_jobs_user', table_name='background_jobs')
    op.drop_index('ix_background_jobs_claim', table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_table('users')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
