"""Safe Markdown rendering for model-authored Telegram replies.

The rest of the bot intentionally remains plain text. Only LLM chat replies go
through this module, so filenames, task titles and other user-authored values do
not globally become Telegram markup.
"""

from __future__ import annotations

import html
import logging
import re
from collections.abc import Sequence
from typing import Any
from urllib.parse import urlparse

from aiogram.exceptions import TelegramBadRequest
from aiogram.types import InlineKeyboardMarkup, Message

from assistant.services.tg_text import TELEGRAM_TEXT_LIMIT, split_for_telegram

logger = logging.getLogger("assistant.telegram_markdown")

_FENCE_RE = re.compile(
    r"```(?P<lang>[A-Za-z0-9_+.-]{0,32})[ \t]*\n?(?P<body>.*?)```",
    re.DOTALL,
)
_INLINE_CODE_RE = re.compile(r"`([^`\n]+)`")
_LINK_RE = re.compile(r"\[([^\]\n]+)\]\(([^)\s]+)\)")
_HEADING_RE = re.compile(r"(?m)^[ \t]{0,3}#{1,6}[ \t]+(.+?)[ \t]*#*[ \t]*$")
_BLOCKQUOTE_RE = re.compile(r"(?m)^[ \t]*(?:>|&gt;)[ \t]?(.*)$")


def _safe_link(url: str) -> bool:
    """Return whether a Markdown link is safe to emit as Telegram HTML."""
    try:
        parsed = urlparse(url)
    except ValueError:
        return False
    return parsed.scheme.lower() in {"http", "https", "tg", "mailto", "tel"}


def markdown_to_telegram_html(text: str) -> str:
    """Convert the Markdown subset commonly produced by Qwen to Telegram HTML.

    Supported: headings, bold, italic, strike, spoiler, inline code, fenced
    code, links, blockquotes and bullet lists.

    Raw model HTML is always escaped. Unsupported Markdown remains readable
    text rather than being passed to Telegram as an unsafe/invalid entity.
    """
    if not text:
        return ""

    source = text.replace("\r\n", "\n").replace("\r", "\n")
    tokens: list[str] = []

    def stash(fragment: str) -> str:
        token = f"@@TGMDTOKEN{len(tokens)}@@"
        tokens.append(fragment)
        return token

    def fenced(match: re.Match[str]) -> str:
        language = match.group("lang").strip()
        body = html.escape(match.group("body"), quote=False)
        if language:
            # Regex already constrains the language, keep a second defensive filter.
            language = re.sub(r"[^A-Za-z0-9_+.-]", "", language)
            return stash(
                f'<pre><code class="language-{language}">{body}</code></pre>'
            )
        return stash(f"<pre>{body}</pre>")

    # Protect code before any other Markdown processing.
    source = _FENCE_RE.sub(fenced, source)
    source = _INLINE_CODE_RE.sub(
        lambda match: stash(f"<code>{html.escape(match.group(1), quote=False)}</code>"),
        source,
    )

    def link(match: re.Match[str]) -> str:
        label = html.escape(match.group(1), quote=False)
        url = match.group(2)
        if not _safe_link(url):
            return stash(f"{label} ({html.escape(url, quote=False)})")
        href = html.escape(url, quote=True)
        return stash(f'<a href="{href}">{label}</a>')

    source = _LINK_RE.sub(link, source)

    # Everything not generated by this module becomes text, never raw HTML.
    rendered = html.escape(source, quote=False)

    rendered = _HEADING_RE.sub(r"<b>\1</b>", rendered)
    rendered = _BLOCKQUOTE_RE.sub(r"<blockquote>\1</blockquote>", rendered)

    # Strong before italic, so **text** is consumed as a single entity.
    rendered = re.sub(r"\*\*([^*\n]+?)\*\*", r"<b>\1</b>", rendered)
    rendered = re.sub(r"__([^_\n]+?)__", r"<b>\1</b>", rendered)
    rendered = re.sub(r"~~([^~\n]+?)~~", r"<s>\1</s>", rendered)
    rendered = re.sub(
        r"\|\|([^|\n]+?)\|\|", r"<tg-spoiler>\1</tg-spoiler>", rendered
    )
    rendered = re.sub(r"(?<!\*)\*([^*\n]+?)\*(?!\*)", r"<i>\1</i>", rendered)

    # Conservative underscore italics: do not break snake_case / filenames.
    rendered = re.sub(r"(?<!\w)_([^_\n]+?)_(?!\w)", r"<i>\1</i>", rendered)

    # Lists are more natural in Telegram with a Unicode bullet.
    rendered = re.sub(r"(?m)^[ \t]*[-*][ \t]+", "• ", rendered)

    for index, fragment in enumerate(tokens):
        rendered = rendered.replace(f"@@TGMDTOKEN{index}@@", fragment)

    return rendered


async def answer_long_markdown(
    message: Message,
    text: str,
    reply_markup: InlineKeyboardMarkup | None = None,
    *,
    limit: int = TELEGRAM_TEXT_LIMIT,
    **kwargs: Any,
) -> Sequence[Message]:
    """Send LLM Markdown as Telegram HTML with a plain-text safety fallback.

    The original Markdown is split first, then every segment is converted
    independently. Therefore a Telegram-size split can never cut an HTML tag.

    If Telegram rejects a formatted segment, only that failed segment is
    retried as the original plain Markdown. Formatting must never make a valid
    assistant answer disappear.
    """
    segments = split_for_telegram(text, limit)
    sent: list[Message] = []

    for index, segment in enumerate(segments):
        base_kwargs = dict(kwargs)
        if index == len(segments) - 1 and reply_markup is not None:
            base_kwargs["reply_markup"] = reply_markup

        html_kwargs = dict(base_kwargs)
        html_kwargs["parse_mode"] = "HTML"

        try:
            sent.append(
                await message.answer(
                    markdown_to_telegram_html(segment),
                    **html_kwargs,
                )
            )
        except TelegramBadRequest:
            logger.warning(
                "Telegram rejected formatted AI reply; retrying segment as plain text",
                exc_info=True,
            )
            # No parse_mode on the retry: preserve the project's plain-text safety model.
            sent.append(await message.answer(segment, **base_kwargs))

    return sent
